/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
          "on-primary-fixed": "#004075",
          "tertiary-dim": "#cecfef",
          "surface-container-high": "#16202e",
          "on-primary": "#004176",
          "surface-container-highest": "#1a2637",
          "on-primary-container": "#b4d2ff",
          "surface-variant": "#1a2637",
          "on-surface-variant": "#9facc1",
          "on-tertiary": "#545671",
          "secondary": "#9c9ea4",
          "surface-bright": "#1e2d41",
          "primary-fixed-dim": "#bbd6ff",
          "inverse-surface": "#f8f9ff",
          "on-background": "#d9e6fd",
          "tertiary-fixed": "#dcddfe",
          "primary-container": "#004882",
          "on-error-container": "#ff9993",
          "on-secondary-fixed": "#3d3f44",
          "error-container": "#7f2927",
          "tertiary": "#edecff",
          "surface-tint": "#a2c9ff",
          "on-tertiary-fixed-variant": "#555873",
          "outline": "#6a768a",
          "secondary-container": "#393b40",
          "on-secondary-fixed-variant": "#595b61",
          "on-tertiary-container": "#4c4e69",
          "surface-dim": "#0a0e14",
          "surface-container-lowest": "#000000",
          "on-tertiary-fixed": "#393c55",
          "on-secondary": "#1e2025",
          "error": "#ee7d77",
          "on-error": "#490106",
          "secondary-dim": "#9c9ea4",
          "secondary-fixed": "#e1e2e8",
          "on-secondary-container": "#bdbfc5",
          "on-primary-fixed-variant": "#005da5",
          "outline-variant": "#3c495b",
          "primary-dim": "#88bcff",
          "primary": "#a2c9ff",
          "inverse-on-surface": "#51555c",
          "surface-container-low": "#0e141c",
          "tertiary-fixed-dim": "#cecfef",
          "error-dim": "#bb5551",
          "inverse-primary": "#0061ab",
          "secondary-fixed-dim": "#d3d4da",
          "background": "#0a0e14",
          "primary-fixed": "#d3e4ff",
          "surface-container": "#121a25",
          "surface": "#0a0e14",
          "tertiary-container": "#dcddfe",
          "on-surface": "#d9e6fd"
      },
      fontFamily: {
          "headline": ["Space Grotesk", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"],
          "mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"]
      },
      borderRadius: {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
